#! /bin/sh
sxhkd &
$HOME/.config/polybar/launch.sh
~/.fehbg
numlockx &
xscreensaver -nosplash &
#picom --config /etc/xdg/compton.conf -b
#flameshot &
xsetroot -cursor_name left_ptr &
# hsetroot -solid "#282829" &

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true


